# HTTP Server
server:
  port: ${PORT:17502}   # HTTP (Tomcat) port
info:
  component: Account Service
 
# LOGGIN CONFIG
---
spring:
  profiles: prod
logging:
  file: logs/account-server.log